name: Build and Push Docker Image

on: 
    push:
        branches:
            - main
    workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: beatrixkiddo
  DOCKER_REGISTRY: docker.io/mariiasharkovska

jobs: 
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Registry
              uses: docker/login-action@v3

              with:
                  registry: ${{ env.DOCKER_REGISTRY }}
                  username: ${{ vars.DOCKERHUB_USERNAME }}  
                  password: ${{ secrets.DOCKERHUB_PAT }}

            # - name: Build and push Docker image
              # uses: docker/build-push-action@v6
              # env:
              #   DOCKER_BUILDKIT: 0
              #   COMPOSE_DOCKER_CLI_BUILD: 0
              # with:
              #   context: .
              #   file: ./Dockerfile
              #   push: true
              #   tags: |
              #       
              #       

            - name: Docker Build
              run: 
                docker build .Dockerfile -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest

            - name: Docker Push
              run: |
                docker login -u mariiasharkovska -p ${{ secrets.DOCKERHUB_PAT }}
                docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
                docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
